image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r ./requirements.txt
    command: pip install pylint autopep8
    name: youcheater

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - ms-python.python@2019.11.50794:o+QLHnb+xFH1zuBM7u1VIw==
